### ISSUE TITLE
Questions about genre embeddings when doing out-of-domain evaluation using SpanBERT model

### ISSUE THREAD

**Issue by Fantabulous-J** [yilunzhu/ontogum#1]
Hi, thanks for sharing such amazing work.

I am wondering how do you map the 12 genres into the OntoNotes 5.0's 7 genre embeddings used in Joshi's SpanBERT model? Did you simply use 0 vectors for all 12 genres or do mapping for some genres? I noticed that there are some shared genres such as speech recordings and newswire.

Thanks for your time.

**Comment by yilunzhu** [comment]
Hi,

Since OntoNotes' genres are different from GUM genres (see below), we do not map the 12 genres into OntoNotes' 7 genres. During the evaluation, we practically use 'bc' to indicate all genres in OntoGUM. 

* For speech data, though both OntoNotes and OntoGUM have data coming from recordings but they are quite different. In OntoGUM, the speech data is political speech from various sources while in OntoNotes the speech data sources from broadcast news (BN), broadcast conversation (BC), and telephone conversation (TC). For newswire, please see some analysis in the paper Section 5 "comparing genres."
